### ISSUE TITLE
Builder doesn't always exist

### ISSUE THREAD

**Issue by isaacseymour** [honeycombio/activerecord-honeycomb#1]
I'm getting a super weird error which only occurs in dev & in the puma server (i.e., not in `rails c`). There's a `undefined method `event' for nil:NilClass` [here](https://github.com/honeycombio/activerecord-honeycomb/blob/master/lib/active_record/connection_adapters/honeycomb_adapter.rb#L91). 

Full trace here:
```
activerecord-honeycomb (0.2.4) lib/active_record/connection_adapters/honeycomb_adapter.rb:91:in `sending_honeycomb_event'
activerecord-honeycomb (0.2.4) lib/active_record/connection_adapters/honeycomb_adapter.rb:69:in `execute'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/schema_statements.rb:242:in `client_min_messages='
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:700:in `configure_connection'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:685:in `connect'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
activerecord-honeycomb (0.2.4) lib/active_record/connection_adapters/honeycomb_adapter.rb:21:in `honeycomb_connection'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
activerecord (5.2.1) lib/active_record/connection_handling.rb:118:in `retrieve_connection'
activerecord (5.2.1) lib/active_record/connection_handling.rb:90:in `connection'
activerecord (5.2.1) lib/active_record/model_schema.rb:466:in `load_schema!'
activerecord (5.2.1) lib/active_record/attributes.rb:234:in `load_schema!'
activerecord (5.2.1) lib/active_record/attribute_decorators.rb:51:in `load_schema!'
activerecord (5.2.1) lib/active_record/model_schema.rb:459:in `block in load_schema'
/Users/isaac/.rbenv/versions/2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.2.1) lib/active_record/model_schema.rb:456:in `load_schema'
activerecord (5.2.1) lib/active_record/model_schema.rb:346:in `attribute_types'
activerecord (5.2.1) lib/active_record/model_schema.rb:370:in `type_for_attribute'
activerecord (5.2.1) lib/active_record/table_metadata.rb:33:in `type'
activerecord (5.2.1) lib/active_record/relation/predicate_builder.rb:51:in `build'
activerecord (5.2.1) lib/active_record/relation/predicate_builder.rb:107:in `block in expand_from_hash'
activerecord (5.2.1) lib/active_record/relation/predicate_builder.rb:71:in `each'
activerecord (5.2.1) lib/active_record/relation/predicate_builder.rb:71:in `flat_map'
activerecord (5.2.1) lib/active_record/relation/predicate_builder.rb:71:in `expand_from_hash'
activerecord (5.2.1) lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
activerecord (5.2.1) lib/active_record/relation/where_clause_factory.rb:19:in `build'
activerecord (5.2.1) lib/active_record/relation/query_methods.rb:591:in `where!'
activerecord (5.2.1) lib/active_record/relation/query_methods.rb:584:in `where'
activerecord (5.2.1) lib/active_record/querying.rb:12:in `where'
app/models/queries/model_queries.rb:93:in `filter_no_longer_made'
activerecord (5.2.1) lib/active_record/relation/delegation.rb:84:in `public_send'
activerecord (5.2.1) lib/active_record/relation/delegation.rb:84:in `block in method_missing'
activerecord (5.2.1) lib/active_record/relation.rb:281:in `scoping'
activerecord (5.2.1) lib/active_record/relation/delegation.rb:84:in `method_missing'
```

For now I've had to remove the beeline to let people run stuff in dev :(

**Comment by isaacseymour** [comment]
We stopped using this gem and rolled our own tracing solution, sorry!
