### ISSUE TITLE
The gem prevents the app to start with Rails 6 beta 1

### ISSUE THREAD

**Issue by renchap** [honeycombio/activerecord-honeycomb#10]
I am testing my app with the newly release Rails 6 beta 1 and it is breaking when deploying with Honeycomb:

```
ActiveRecord::AdapterNotSpecified: ActiveRecord::AdapterNotSpecified
  ./shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0.beta1/lib/active_record/connection_adapters/connection_specification.rb:142:in `resolve'
  ./shared/bundle/ruby/2.6.0/gems/activerecord-honeycomb-0.4.0/lib/active_record/honeycomb.rb:30:in `resolve_config'
  ./shared/bundle/ruby/2.6.0/gems/activerecord-honeycomb-0.4.0/lib/active_record/honeycomb.rb:7:in `munge_config'
  ./shared/bundle/ruby/2.6.0/gems/activerecord-honeycomb-0.4.0/lib/activerecord-honeycomb/auto_install.rb:20:in `block (2 levels) in auto_install!'
  ./shared/bundle/ruby/2.6.0/gems/activerecord-import-0.28.1/lib/activerecord-import/import.rb:242:in `establish_connection_with_activerecord_import'
  ./shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0.beta1/lib/active_record/railtie.rb:193:in `block (2 levels) in <class:Railtie>'
  ./shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0.beta1/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
  ./shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0.beta1/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
  ./shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0.beta1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
  ./shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0.beta1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
  ./shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0.beta1/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
  ./shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0.beta1/lib/active_support/lazy_load_hooks.rb:42:in `each'
  ./shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0.beta1/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
  ./shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0.beta1/lib/active_record/railtie.rb:191:in `block in <class:Railtie>'
  ./shared/bundle/ruby/2.6.0/gems/railties-6.0.0.beta1/lib/rails/initializable.rb:32:in `instance_exec'
  ./shared/bundle/ruby/2.6.0/gems/railties-6.0.0.beta1/lib/rails/initializable.rb:32:in `run'
  ./shared/bundle/ruby/2.6.0/gems/railties-6.0.0.beta1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /usr/local/rbenv/versions/2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  ./shared/bundle/ruby/2.6.0/gems/railties-6.0.0.beta1/lib/rails/initializable.rb:60:in `run_initializers'
  ./shared/bundle/ruby/2.6.0/gems/railties-6.0.0.beta1/lib/rails/application.rb:361:in `initialize!'
  ./releases/20190126144941/config/environment.rb:7:in `<top (required)>'
  config.ru:9:in `require_relative'
  config.ru:9:in `block in <main>'
  ./shared/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  ./shared/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  ./shared/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
  ./shared/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
  ./shared/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
  ./shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
  ./shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
  ./shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
  ./shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
  ./shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
  ./shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
  ./shared/bundle/ruby/2.6.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
  ./shared/bundle/ruby/2.6.0/bin/puma:23:in `load'
  ./shared/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
```

When disabling the beeline in `config.ru` the app works fine.

I am not sure whats happening here. While upgrading I noticed that when loading YAML config (like `database.yml`) Rails is now using a hash with symbols as keys, where it before accepted strings in getters, maybe it is related?

**Comment by jeremy** [comment]
FYI, Rails 6 is in release candidate now. (This blocked me from trialing Honeycomb on a Rails 6 app.)

**Comment by eanakashima** [comment]
@jeremy @renchap hey, thanks for the report, and sorry for the delayed response. We are working on a longer-term architectural solution that changes the way the beeline is configured that I believe will fix this, but I will also see if we can look into whether there's a quick fix that would unblock using us with a Rails 6 app sooner.

**Comment by martin308** [comment]
@renchap @Jeremy `v1.0.0` has been released now which should support rails 6!
